### ISSUE TITLE
[Bug]: Cannot install the package because it conflicted with another require

### ISSUE THREAD

**Issue by fahmiegerton** [ibrahimBougaoua/RadioButtonImage#12]
### What happened?

I cannot install the package, it seems cannot load illuminate/contracts. Here's my compooser dependencies
```
    "require": {
        "php": "^8.2",
        "filament/filament": "^3.2",
        "laravel/framework": "^11.9",
        "laravel/tinker": "^2.9",
        "awcodes/light-switch": "^1.0",
        "aymanalhattami/filament-context-menu": "^1.0",
        "bezhansalleh/filament-shield": "^3.2",
        "duitkupg/duitku-php": "dev-master",
        "swisnl/filament-backgrounds": "^1.1",
        "tomatophp/filament-users": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^3.1",
        "fakerphp/faker": "^1.23",
        "laravel-lang/common": "^6.4",
        "laravel/pint": "^1.13",
        "laravel/sail": "^1.26",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.0",
        "pestphp/pest": "^2.34",
        "pestphp/pest-plugin-laravel": "^2.4"
    },
```

### How to reproduce the bug

Problem 1
    - Root composer.json requires ibrahimbougaoua/radiobuttonimage * -> satisfiable by ibrahimbougaoua/radiobuttonimage[v1.0.0, v1.1.2].
    - ibrahimbougaoua/radiobuttonimage[v1.0.0, ..., v1.1.2] require illuminate/contracts ^10.0 -> found illuminate/contracts[v10.0.0, ..., v10.48.17] but these were not loaded, likely because it conflicts with another require.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require ibrahimbougaoua/radiobuttonimage:*" to figure out if any version is installable, or "composer require ibrahimbougaoua/radiobuttonimage:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Package Version

1.1.2

### PHP Version

8.2.0

### Laravel Version

11

### Which operating systems does with happen with?

Windows

**Comment by holmesadam** [comment]
I've opened a pull request to bump illuminate/contracts to v11 in #13

**Comment by ibrahimBougaoua** [comment]
> I've opened a pull request to bump illuminate/contracts to v11 in #13

Thanks.
